# Numpy

The Numpy is a C extension for Python that is fundamental to scientific computing.
It has a number of features that facilitate the use of vectors and matrices.

Contains among other things:
* N-dimensional objects with powerful features;
* Sophisticated and extensive functions;
* Tools to integrate C / C ++ and Fortran code;
* Tools of linear algebra, Fourier transform among others.


As we move forward, try to imagine doing the same thing using only basic Python functions and lists.


In [1]:
import numpy as np

In [3]:
vector = np.array([1., 4., 5.3, 2.9])

In [5]:
type(vector)

numpy.ndarray

In [6]:
vector[2:3]

array([5.3])

Arrays are very similar to lists at various points, such as partitioning. However, we started to see some built-in functions:

In [8]:
print('Maximum value: ', vector.max())
print('Mean value: ', vector.mean())
print('Standard Deviation: ', vector.std())
print('Variance: ', vector.var())

Maximum value:  5.3
Mean value:  3.3000000000000003
Standard Deviation:  1.5763882770434445
Variance:  2.4849999999999994


We are dealing with a small vector, but one of the things we need to know is the length of the vector:

In [9]:
vector.shape

(4,)

Would you need it to be a list again?

In [10]:
vector.tolist()

[1.0, 4.0, 5.3, 2.9]

## Matrices

So far it Numpy array and lists seems very similar. You probably thought, "I can do this with a list". Yes, you can. But now let's complicate it a little. How about we work with matrices?

In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6]], float)
matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

Now the functions we saw are more interesting:

In [13]:
matrix.max()

6.0

In [12]:
matrix.shape

(2, 3)

We also have several functions to change the size of the matrix and / or transpose the matrix

In [14]:
matrix.reshape(3, 2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [15]:
matrix.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [16]:
matrix.flatten()

array([1., 2., 3., 4., 5., 6.])

# Matrix operation

Now we need to talk about axis. Since we are now talking about 2 dimensions (but Numpy support many more), you sometimes need to define in which axis you want to apply a certain function. In Python the axis 0 representes the rows while axis 1 represents the columns.

Let's say you have two matrices and want to join them. Numpy has the method `concatenate`:

In [21]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)

print('Matrix A')
print(a)
print('Matrix B')
print(b)

Matrix A
[[1. 2.]
 [3. 4.]]
Matrix B
[[5. 6.]
 [7. 8.]]


In [18]:
# axis 0 is the default value
np.concatenate((a,b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [19]:
np.concatenate((a,b), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

## Other ways to create matrices and vectors

In [23]:
# Spaced intervals
np.arange(1., 6., 0.33, dtype=float)

array([1.  , 1.33, 1.66, 1.99, 2.32, 2.65, 2.98, 3.31, 3.64, 3.97, 4.3 ,
       4.63, 4.96, 5.29, 5.62, 5.95])

In [24]:
# Array of zeros
np.zeros(7, dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [25]:
# Array of ones
np.ones((2,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# Identity matrix
np.identity(4, dtype=float)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Let's talk about math

One of the biggest problems with working with lists instead of vectors, is performing mathematical operations on all elements of the list. In general, in a list, we need to go through all the elements to do the operations. This results in low performance, which can be really harmful if we are talking about several rows of data.

Mathematical operations with vectors and matrices are much faster and more efficient than iterations. Numpy allows this type of operation to happen in a very simple way:

In [26]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)

In [21]:
a + b

array([ 6.,  4.,  9.])

In [22]:
a - b

array([-4.,  0., -3.])

In [23]:
a * b

array([  5.,   4.,  18.])

In [24]:
b / a

array([ 5.,  1.,  2.])

In [25]:
a % b

array([ 1.,  0.,  3.])

In [26]:
b ** a

array([   5.,    4.,  216.])

In [27]:
a > b

array([False, False, False], dtype=bool)

## Default values

As well as functions, Numpy also has values that are useful to use

In [28]:
np.pi

3.141592653589793

In [29]:
np.e

2.718281828459045

In [30]:
np.nan

nan

In [31]:
np.inf

inf

In [32]:
a = np.array([1, np.nan, 10], float)
np.isnan(a)

array([False,  True, False], dtype=bool)

## Even more magic!

In [33]:
a = np.array([[1, 2], [3, 4]], float)
a.diagonal()

array([ 1.,  4.])

In [34]:
a = np.array([0.5, 3, 1], float)
np.where(a > 1, 1/a, a)

array([ 0.5       ,  0.33333333,  1.        ])

Documentation was renewed a couple of weeks ago, so you should [totally check it out!](https://numpy.org/doc/1.19/user/quickstart.html)